### ISSUE TITLE
Programm does not start in Dgpu mode in Flatpack-version

### ISSUE THREAD

**Issue by Itshardtogiveyourselfaname** [flathub/com.modrinth.ModrinthApp#10] opened 2024-07-07 10:30 UTC
**Describe the bug**

Im using a Notebook with Pop!OS with a Nvidia dGPU and AMD Processor with iGPU. Not only do I also encounter the  issue#9 (config of environmental variables not working), but when I switch from any of the following graphics modes (Integrated Graphics, Compute Graphics or Hybrid Graphics) to Nvidia Graphics mode (dGPU) and try to launch the program, I get a gray colored window displaying nothing. The UI seem to be still loading in some way, as the mouse cursor symbol changes by hovering over certain spots of the window. The AppImage version on the other hand works perfectly fine. 

**Steps to reproduce**

Launch Program with a Nvidia dGPU only

**System information**

OS    Pop 22.04 jammy
Kernel: x86_64 Linux 6.9.3-76060903-generic
DE: Gnome 42.9
WM: Mutter (X11)
CPU: AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx
GPU: TU117M [GeForce GTX 1650 Mobile / Max-Q]  (nvidia-driver-550.67)
RAM: 16GB

**Comment by ws909** [comment] 2024-08-19 17:12
Same here. The Flatpak version does not work, no matter if I install it from the terminal, Pop!_Shop or Cosmic App Store. The AppImage version does work. I'm on a desktop, using the GPU, and I haven't tested with integrated graphics. The application window opens, but nothing ever renders to it (except for the grey colour and round corners). I did not notice any cursor changes.

Operating System: Pop!_OS 22.04 LTS
CPU: Intel i9-14900K
GPU: NVIDIA GeForce RTX 4080 SUPER
NVIDIA Driver Version: 555.58.02
Windowing system: X11 (default)
Gnome version: 42.9

**Comment by getchoo** [comment] 2024-09-25 18:54
Duplicate of #9. Hopefully I'll be able to work this out soon

**Closed by getchoo** 2024-09-25 18:54 UTC

**Comment by ws909** [comment] 2024-09-25 18:56
@getchoo Eh, the performance was atrocious. That should not be the case on an i9-14900K's integrated graphics. I've run games on this CPU's graphics.

**Comment by getchoo** [comment] 2024-09-25 18:59
Lesser than expected performance on an iGPU would be a separate issue. This was reporting dGPUs not working as intended

**Comment by ws909** [comment] 2024-09-25 19:03
Right, I think I may have messed up the reporting location. My bad. Anyway, I'm using Prism now, so I won't pursue this further.
